# Generated by Django 4.2.14 on 2025-06-27 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUsageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100, verbose_name="API名称")),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="总请求数"),
                ),
                (
                    "successful_requests",
                    models.IntegerField(default=0, verbose_name="成功请求数"),
                ),
                (
                    "failed_requests",
                    models.IntegerField(default=0, verbose_name="失败请求数"),
                ),
                (
                    "total_execution_time",
                    models.FloatField(default=0, verbose_name="总执行时间"),
                ),
                (
                    "total_request_size",
                    models.BigIntegerField(default=0, verbose_name="总请求大小"),
                ),
                (
                    "total_response_size",
                    models.BigIntegerField(default=0, verbose_name="总响应大小"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "API使用统计",
                "verbose_name_plural": "API使用统计",
                "db_table": "api_usage_statistics",
                "ordering": ["-date", "-total_requests"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="api_usage_s_user_id_9850c0_idx"
                    ),
                    models.Index(
                        fields=["api_name", "date"],
                        name="api_usage_s_api_nam_093c2e_idx",
                    ),
                ],
                "unique_together": {("user", "api_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="APIAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                ("api_name", models.CharField(max_length=100, verbose_name="API名称")),
                ("api_path", models.CharField(max_length=200, verbose_name="API路径")),
                (
                    "http_method",
                    models.CharField(max_length=10, verbose_name="HTTP方法"),
                ),
                (
                    "request_data",
                    models.JSONField(blank=True, null=True, verbose_name="请求数据"),
                ),
                (
                    "request_params",
                    models.JSONField(blank=True, null=True, verbose_name="请求参数"),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(blank=True, null=True, verbose_name="响应数据"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时间(秒)"
                    ),
                ),
                (
                    "request_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="请求大小(字节)"
                    ),
                ),
                (
                    "response_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应大小(字节)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "api_version",
                    models.CharField(
                        default="v1", max_length=20, verbose_name="API版本"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "API访问记录",
                "verbose_name_plural": "API访问记录",
                "db_table": "api_access_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="api_access__user_id_79a921_idx",
                    ),
                    models.Index(
                        fields=["api_name", "created_at"],
                        name="api_access__api_nam_b228da_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="api_access__ip_addr_a0a37e_idx",
                    ),
                    models.Index(
                        fields=["is_success", "created_at"],
                        name="api_access__is_succ_ef8f56_idx",
                    ),
                ],
            },
        ),
    ]
