# Generated by Django 4.2.14 on 2025-06-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置名称"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="你是一个有用的AI助理。", verbose_name="系统提示词"
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        default="openai", max_length=20, verbose_name="模型类型"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-3.5-turbo", max_length=50, verbose_name="模型名称"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=2000, verbose_name="最大token数"),
                ),
                ("temperature", models.FloatField(default=0.7, verbose_name="温度")),
                (
                    "max_history",
                    models.IntegerField(default=10, verbose_name="最大历史消息数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "助理配置",
                "verbose_name_plural": "助理配置",
                "db_table": "ai_assistant_config",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="用户ID")),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="新对话", max_length=200, verbose_name="对话标题"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
            ],
            options={
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
                "db_table": "ai_assistant_conversation",
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="工具名称"
                    ),
                ),
                ("description", models.TextField(verbose_name="工具描述")),
                (
                    "function_name",
                    models.CharField(max_length=100, verbose_name="函数名称"),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="参数定义")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "工具",
                "verbose_name_plural": "工具",
                "db_table": "ai_assistant_tool",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "助理"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="使用的token数"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_assistant.conversation",
                        verbose_name="对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "ai_assistant_message",
                "ordering": ["created_at"],
            },
        ),
    ]
