# Generated by Django 4.2.14 on 2025-06-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "通用"),
                            ("coding", "编程"),
                            ("writing", "写作"),
                            ("analysis", "分析"),
                            ("translation", "翻译"),
                            ("creative", "创意"),
                            ("education", "教育"),
                            ("business", "商业"),
                            ("other", "其他"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("description", models.TextField(verbose_name="模板描述")),
                ("keywords", models.JSONField(default=list, verbose_name="关键词列表")),
                ("prompt_template", models.TextField(verbose_name="提示词模板")),
                ("variables", models.JSONField(default=list, verbose_name="模板变量")),
                ("priority", models.IntegerField(default=1, verbose_name="优先级")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "提示词模板",
                "verbose_name_plural": "提示词模板",
                "db_table": "ai_assistant_prompt_template",
                "ordering": ["-priority", "-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="PromptSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField(verbose_name="用户消息")),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="置信度"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_selections",
                        to="ai_assistant.conversation",
                        verbose_name="对话",
                    ),
                ),
                (
                    "selected_prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistant.prompttemplate",
                        verbose_name="选择的提示词",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词选择记录",
                "verbose_name_plural": "提示词选择记录",
                "db_table": "ai_assistant_prompt_selection",
            },
        ),
    ]
